name: "Prepare files for release"

description: "Modifies various files in preparation for release"

inputs:
  repo-token:
    description: "Token with permissions to do repo things"
    required: false
  tag-version-string:
    description: "The string specifying what new version we are releasing"
    required: false
outputs:
  new-networking-version:
    description: "The networking version our photonNetworkingVersion has been set to"

runs:
  using: "node12"
  main: "dist/index.js"
