name: Create New Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version tag'
        default: 'v1.0.0'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Prepare Files For Release 
        run: |
          python -m pip install --upgrade pip
          pip install -U unityparser
          python .github/workflows/script.py
      - name: "Add, Commit And Push Prepared Files"
        run: |
          git config --global user.email "releasebot@users.noreply.github.com"
          git config --local user.name "release bot"
          git add -A
          git commit -m "Update Photon Networking code to ${{ steps.prepare-files.outputs.new-networking-version }}"
          git push
      - name: "Merge Master Into Release"
        run: |
          git fetch
          git checkout release
          git merge master --no-ff
          git push
      - name: "Tag Release"
        run: |
          git tag ${{ github.event.inputs.release-version }}
          git push --tags
