name: Create New Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version tag'
        default: 'v1.0.0'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Release Action"
      uses: ./.github/actions/new-release
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag-version-string: ${{ github.event.inputs.release-version }}
    - name: "Add Commit And Push"
      run: |
        git config --global user.email "thsbrown@users.noreply.github.com"
        git config --local user.name "Thomas"
        git add -A
        git commit -m "Update Photon Networking code to release number"
        git push
